"""Add user, product, test_table tables

Revision ID: 10106e08bc46
Revises: b3d812f8250c
Create Date: 2025-08-12 23:31:22.462744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10106e08bc46'
down_revision = 'b3d812f8250c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
