"""privilege test

Revision ID: 41cbc2e1f8e5
Revises: 743d066f167e
Create Date: 2025-08-12 22:16:29.415256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cbc2e1f8e5'
down_revision = '743d066f167e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
