"""test migration

Revision ID: 743d066f167e
Revises: 
Create Date: 2025-08-12 21:51:03.228935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743d066f167e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
