"""Add user, product, test_table tables

Revision ID: 83b1d0c4ee72
Revises: a54cddb975a2
Create Date: 2025-08-12 23:40:50.032680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b1d0c4ee72'
down_revision = 'a54cddb975a2'
branch_labels = None
depends_on = None

def upgrade():
    # Create 'user' table
    op.create_table(
        'user',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False, unique=True)
    )

    # Create 'product' table
    op.create_table(
        'product',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('price', sa.Numeric(10, 2), nullable=False)
    )

    # Create 'test_table' table
    op.create_table(
        'test_table',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('data', sa.String(length=255))
    )

#def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
