"""Add user, product, test_table tables

Revision ID: a54cddb975a2
Revises: 10106e08bc46
Create Date: 2025-08-12 23:32:43.198808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54cddb975a2'
down_revision = '10106e08bc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
