"""add test_table

Revision ID: b3d812f8250c
Revises: 41cbc2e1f8e5
Create Date: 2025-08-12 23:24:40.120044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d812f8250c'
down_revision = '41cbc2e1f8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
